///|
pub const PIXI_SLOT_LEFT_X : Double = 0.05

///|
pub const PIXI_SLOT_CENTER_X : Double = 0.30

///|
pub const PIXI_SLOT_RIGHT_X : Double = 0.55

///|
pub const PIXI_SLOT_Y_RATIO : Double = 0.1

///|
pub const PIXI_CUSTOM_ANIM_COORD_BIAS : Double = 1000.0

///|
pub const DOM_POS_LEFT_X : Double = 0.18

///|
pub const DOM_POS_CENTER_X : Double = 0.5

///|
pub const DOM_POS_RIGHT_X : Double = 0.82

///|
pub const DOM_POS_MID_Y : Double = 0.5
